version: "3"
services:
  hrm-db-prod:
    image: mongo:latest
    container_name: "hrm-db-prod"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/kaustubh/Desktop/HRM/mongo_data/db/:/data/db
  hrm-backend-prod:
    image: hrm-backend
    container_name: "hrm-backend-prod"
    ports:
      - 8081:8081
    links:
      - hrm-db-prod