version: "3"
services:
# Users with AMD processor have a different mongo base image : https://hub.docker.com/r/arm64v8/mongo/
  hrm-db-test-prod-1:
    image: mongo:latest
    container_name: "hrm-db-1"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/kaustubh/Desktop/OmniHRM/starter_data/db:/data/db
  hrm-backend-test-1:
    image: hrm-backend
    container_name: "hrm-be-1"
    ports:
      - 8081:8081
    links:
      - hrm-db-test-prod-1
    environment:
      MONGO_URL: mongodb://admin:password@hrm-db-1:27017/demo1?authSource=admin

  hrm-frontend-test-1:
    image: hrm-fe
    container_name: "hrm-frontend-1"
    ports:
      - 5173:5173
    depends_on:
      - hrm-backend-test-1
      - hrm-db-test-prod-1
    links:
      - hrm-backend-test-1
      - hrm-db-test-prod-1