version: '3.8'

services:

  db:
    image: mongo:latest
    volumes:
      - /starter_data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  
  backend:
    build: 
      context: ./performance-management
    ports:
      - "8081:8081"
    environment:
      - MONGO_URL=mongodb://admin:password@db:27017
    
  
  frontend:
    build:
      context: ./hrm-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - db
