version: "3"
services:
# Users with AMD processor have a different mongo base image : https://hub.docker.com/r/arm64v8/mongo/
  hrm-db-test-prod-1:
    image: mongo:latest
    container_name: db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/kaustubh/Desktop/OmniHRM/starter_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 2
  hrm-backend-test-1:
    image: hrm-be:latest
    container_name: backend
    ports:
      - 8081:8081
    depends_on:
      - hrm-db-test-prod-1
    environment:
      - MONGO_URL=mongodb://admin:password@hrm-db-test-prod-1:27017/demo1?authSource=admin

  hrm-frontend-test-1:
    image: hrm-fe:latest
    container_name: frontend
    ports:
      - 5173:5173
    depends_on:
      - hrm-backend-test-1
      - hrm-db-test-prod-1
    links:
      - hrm-backend-test-1
      - hrm-db-test-prod-1
