version: '3.1'
services:
  app:
    container_name: logtime2
    image: logtime2
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgressql
  postgressql:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=TABLE
